-- 코드를 입력하세요
WITH SALES_1 AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01"
    GROUP BY BOOK_ID
),
TOTAL_SALES_1 AS (
    SELECT B.CATEGORY, B.AUTHOR_ID, SUM(B.PRICE * A.SALES) AS SALES
    FROM SALES_1 AS A, BOOK AS B
    WHERE A.BOOK_ID = B.BOOK_ID
    GROUP BY AUTHOR_ID, CATEGORY
)

# SELECT * FROM TOTAL_SALES_1
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.SALES AS TOTAL_SALES
FROM AUTHOR AS A, TOTAL_SALES_1 AS B
WHERE A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;