-- 코드를 작성해주세요
WITH ABLE AS (
    SELECT DISTINCT A.ITEM_ID
    FROM ITEM_INFO AS A
    INNER JOIN ITEM_TREE AS B ON A.ITEM_ID = B.PARENT_ITEM_ID
    )
    
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (
    SELECT ITEM_ID
    FROM ABLE
)
ORDER BY ITEM_ID DESC;