-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(B.SALES_AMOUNT) * A.PRICE AS SALES
FROM PRODUCT AS A
INNER JOIN OFFLINE_SALE AS B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;