-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (
    SELECT A.ANIMAL_ID, A.NAME, DATEDIFF(B.DATETIME, A.DATETIME) AS DATES
    FROM ANIMAL_INS AS A, ANIMAL_OUTS AS B
    WHERE A.ANIMAL_ID = B.ANIMAL_ID
    ORDER BY DATES DESC
    LIMIT 2
    ) AS C
