WITH NOT_ABLE AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= DATE("2022-11-30")
        AND DATE("2022-11-01") <= END_DATE
), ABLE AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID FROM NOT_ABLE
    ) AND CAR_TYPE IN ("세단", "SUV")
), SALE_FEE AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE IN ("세단", "SUV")
        AND DURATION_TYPE = "30일 이상"
), RENT_FEE AS (
    SELECT A.CAR_ID, A.CAR_TYPE, 
        A.DAILY_FEE * 30 * (100-B.DISCOUNT_RATE) / 100 AS FEE
    FROM ABLE AS A
    LEFT JOIN SALE_FEE AS B
    ON A.CAR_TYPE = B.CAR_TYPE
)

SELECT CAR_ID, CAR_TYPE, ROUND(FEE, 1) AS FEE
FROM RENT_FEE
WHERE 500000 <= FEE AND FEE <= 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;

