-- 코드를 입력하세요


WITH D AS (
    SELECT A.CAR_ID, CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR AS A
    WHERE CAR_TYPE IN ('세단', 'SUV')
    AND CAR_ID NOT IN (
        SELECT DISTINCT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE NOT (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30')
    )
)


SELECT C.CAR_ID, D.CAR_TYPE, ROUND(C.FEE) AS FEE
FROM (
    SELECT A.CAR_ID, A.DAILY_FEE * 30 * (100-DISCOUNT_RATE) / 100 AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS B ON A.CAR_TYPE = B.CAR_TYPE
    WHERE B.DURATION_TYPE = '30일 이상'
) AS C
JOIN D ON D.CAR_ID = C.CAR_ID
WHERE FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;

# SELECT * FROM CAR_RENTAL_COMPANY_CAR
# SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN


