-- 코드를 입력하세요
WITH TOP_F AS (
    SELECT MAX(FAVORITES) AS TOP, FOOD_TYPE
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    )
    
SELECT A.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
FROM TOP_F AS A, REST_INFO AS B
WHERE A.FOOD_TYPE = B.FOOD_TYPE AND A.TOP = B.FAVORITES
ORDER BY FOOD_TYPE DESC;