# SELECT ID, (
#     CASE
#         WHEN RANKING / CNT <= 0.25 THEN "CRITICAL"
#         WHEN RANKING / CNT <= 0.5 THEN "HIGH"
#         WHEN RANKING / CNT <= 0.75 THEN "MEDIUM"
#         ELSE "LOW"
#     END
# ) AS COLONY_NAME
# FROM (
#     SELECT ID, SIZE_OF_COLONY,
#         RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RANKING,
#         COUNT(ID) OVER() AS CNT
#     FROM ECOLI_DATA
# ) AS A
# ORDER BY ID ASC;

SELECT A.ID, (
    CASE
        WHEN PER <= 0.25 THEN 'CRITICAL'
        WHEN PER <= 0.5 THEN 'HIGH'
        WHEN PER <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END 
) AS COLONY_NAME
FROM(
    SELECT ID,
    PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
    FROM ECOLI_DATA
) AS A
ORDER BY ID