-- 코드를 입력하세요

WITH IN_INTACT AS (
    SELECT * 
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE IN ('Intact Male', 'Intact Female')
), OUTS_NOT_INTACT AS (
    SELECT *
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME NOT IN ('Intact Male', 'Intact Female')
)

SELECT IN_INTACT.ANIMAL_ID, IN_INTACT.ANIMAL_TYPE, IN_INTACT.NAME
FROM IN_INTACT
JOIN OUTS_NOT_INTACT ON IN_INTACT.ANIMAL_ID = OUTS_NOT_INTACT.ANIMAL_ID
ORDER BY ANIMAL_ID ASC

# SELECT * FROM IN_INTACT