WITH CTE AS (
    SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
    FROM REST_INFO
    WHERE ADDRESS LIKE "서울%"
), CTE_2 AS (
    SELECT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS,
        COALESCE(REVIEW_SCORE, 0) AS SCORE
    FROM CTE AS A
    LEFT JOIN REST_REVIEW AS B ON A.REST_ID = B.REST_ID
)

SELECT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, 
    ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE 
FROM CTE AS A
JOIN REST_REVIEW AS B ON A.REST_ID = B.REST_ID
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC