-- 코드를 입력하세요
WITH CTE AS (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, 
        B.USER_ID, B.GENDER
    FROM ONLINE_SALE AS A, USER_INFO AS B
    WHERE A.USER_ID = B.USER_ID AND B.GENDER IS NOT NULL
    GROUP BY YEAR, MONTH, USER_ID
)

SELECT YEAR, MONTH, GENDER, COUNT(*)
FROM CTE
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
