-- 코드를 입력하세요
# SELECT * FROM ANIMAL_INS
# SELECT * FROM ANIMAL_OUTS

WITH IN_AND_OUT AS (
    SELECT DISTINCT OUTS.ANIMAL_ID
    FROM ANIMAL_OUTS AS OUTS
    JOIN ANIMAL_INS AS INS ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
)

SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (
    SELECT * FROM IN_AND_OUT
)
ORDER BY ANIMAL_ID