-- 코드를 입력하세요

# SELECT * FROM ONLINE_SALE ORDER BY USER_ID
WITH USER_CNT AS (
    SELECT COUNT(A.USER_ID) AS CNT
    FROM USER_INFO AS A
    WHERE JOINED BETWEEN '2021.01.01' AND '2021.12.31'
), DATE_INFO AS (
        SELECT DISTINCT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, A.USER_ID AS PURCHASED_USERS
    FROM USER_INFO AS A
    JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID
    WHERE JOINED BETWEEN '2021.01.01' AND '2021.12.31'
    # GROUP BY YEAR, MONTH
), DATE_INFO_TWO AS (
    SELECT DATE_INFO.YEAR, DATE_INFO.MONTH, COUNT(PURCHASED_USERS) AS PURCHASED_USERS
    FROM DATE_INFO
    GROUP BY YEAR, MONTH
)

SELECT A.YEAR, A.MONTH, A.PURCHASED_USERS, ROUND(A.PURCHASED_USERS / B.CNT, 1) AS PURCHASED_RATIO
FROM DATE_INFO_TWO AS A, USER_CNT AS B
ORDER BY YEAR ASC, MONTH ASC

# SELECT * FROM ONLINE_SALE
# ORDER BY SALES_DATE
# SELECT * FROM DATE_INFO_TWO