-- 코드를 작성해주세요

WITH RECURSIVE GEN(ID, GENERATION) AS(
    SELECT ID, 1
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION
    
    SELECT E.ID, GEN.GENERATION+1
    FROM GEN
    JOIN ECOLI_DATA AS E ON E.PARENT_ID = GEN.ID 
)

# SELECT DISTINCT GEN.ID, GENERATION
# FROM GEN
# JOIN ECOLI_DATA AS E ON E.PARENT_ID = GEN.ID

SELECT COUNT(GENERATION) AS COUNT, GENERATION
FROM ECOLI_DATA AS E
JOIN GEN ON E.ID = GEN.ID 
WHERE E.ID NOT IN (
    SELECT DISTINCT GEN.ID
    FROM GEN
    JOIN ECOLI_DATA AS E ON E.PARENT_ID = GEN.ID
)
GROUP BY GENERATION
ORDER BY GENERATION ASC
