-- 코드를 입력하세요
WITH NOT_AVAILABLE AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= DATE("2022-10-16")
        AND DATE("2022-10-16") <= END_DATE
    ORDER BY CAR_ID DESC
), CAR_ID_LIST AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT CAR_ID, (
    CASE
    WHEN CAR_ID IN (SELECT * FROM NOT_AVAILABLE)
    THEN "대여중"
    ELSE "대여 가능"
    END
) AS AVAILABILITY
FROM CAR_ID_LIST
ORDER BY CAR_ID DESC;