SELECT A.PRODUCT_ID, B.PRODUCT_NAME, SUM(A.AMOUNT * B.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER AS A, FOOD_PRODUCT AS B
WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m") = "2022-05"
    AND A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC;