-- 코드를 입력하세요
WITH TRUCK_DC AS (
    SELECT (
        CASE
        WHEN DURATION_TYPE = "7일 이상" THEN 7
        WHEN DURATION_TYPE = "30일 이상" THEN 30
        ELSE 90
        END
    ) AS DURATION, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = "트럭"
), HIS_DATE AS (
    SELECT HISTORY_ID, CAR_ID, (DATEDIFF(END_DATE, START_DATE) + 1) AS DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_TYPE = "트럭"
    )
)

SELECT HISTORY_ID, (
    CASE
    WHEN DATE >= 90 THEN FEE * (100 - (
        SELECT DISCOUNT_RATE
        FROM TRUCK_DC
        WHERE DURATION = 90
    )) / 100
    WHEN DATE >= 30 THEN FEE * (100 - (
        SELECT DISCOUNT_RATE
        FROM TRUCK_DC
        WHERE DURATION = 30
    )) / 100
    WHEN DATE >= 7 THEN FEE * (100 - (
        SELECT DISCOUNT_RATE
        FROM TRUCK_DC
        WHERE DURATION = 7
    )) / 100
    ELSE FEE
    END
) AS FEE
FROM (
    SELECT A.HISTORY_ID, A.DATE * B.DAILY_FEE AS FEE, A.DATE
    FROM HIS_DATE AS A, CAR_RENTAL_COMPANY_CAR AS B
    WHERE A.CAR_ID = B.CAR_ID
) AS C
ORDER BY FEE DESC, HISTORY_ID DESC;