-- 코드를 입력하세요
WITH A AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER 
    FROM FIRST_HALF 
    GROUP BY FLAVOR
),
 B AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER 
    FROM JULY 
    GROUP BY FLAVOR 
),
A_ORDER AS (
    SELECT A.FLAVOR, A.TOTAL_ORDER + B.TOTAL_ORDER AS TOTAL_ORDER
    FROM A
    LEFT JOIN B ON A.FLAVOR = B.FLAVOR
)

SELECT FLAVOR
FROM (
    SELECT *
    FROM A_ORDER

    UNION

    SELECT *
    FROM B
    WHERE FLAVOR NOT IN (
        SELECT FLAVOR
        FROM A_ORDER
    )
    ORDER BY TOTAL_ORDER DESC    
) AS TOTAL_ORDER
LIMIT 3





