-- 코드를 입력하세요
SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, C.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A, PATIENT AS B, DOCTOR AS C
WHERE C.MCDP_CD = "CS"
    AND DATE_FORMAT(APNT_YMD, "%Y-%m-%d") = "2022-04-13"
    AND A.PT_NO = B.PT_NO
    AND A.MDDR_ID = C.DR_ID
    AND A.APNT_CNCL_YN = "N"
ORDER BY A.APNT_YMD ASC
    