-- 코드를 작성해주세요
WITH FE AS (
    SELECT SUM(CODE) AS FE_CODE
    FROM SKILLCODES
    WHERE CATEGORY = "Front End"
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (
    SELECT FE_CODE
    FROM FE
) <> 0
ORDER BY ID ASC;
