-- 코드를 입력하세요
WITH NEW_USER AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)

SELECT B.USER_ID, NICKNAME, A.TOTAL_SALES
FROM NEW_USER AS A, USED_GOODS_USER AS B
WHERE A.WRITER_ID = B.USER_ID
ORDER BY A.TOTAL_SALES ASC;