-- 코드를 입력하세요
# SELECT * FROM MEMBER_PROFILE;

WITH MAX_REVIEW AS (
    SELECT MEMBER_ID, COUNT(MEMBER_ID) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY CNT DESC
    LIMIT 1
)

SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS A
JOIN MEMBER_PROFILE AS B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM MAX_REVIEW
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;



