SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM REST_REVIEW AS A, MEMBER_PROFILE AS B
WHERE A.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
    ) AND A.MEMBER_ID = B.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC