-- 코드를 작성해주세요


SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM (
    SELECT B.ITEM_ID
    FROM ITEM_INFO AS A
    JOIN ITEM_TREE AS B ON B.PARENT_ITEM_ID = A.ITEM_ID
    WHERE A.RARITY = 'RARE' AND B.PARENT_ITEM_ID IS NOT NULL
) AS D
JOIN ITEM_INFO AS C ON C.ITEM_ID = D.ITEM_ID
ORDER BY C.ITEM_ID DESC;




