WITH PY AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = "Python"
), CSHARP AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = "C#"
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT * FROM PY) = (SELECT * FROM PY)
    OR SKILL_CODE & (SELECT * FROM CSHARP) = (SELECT * FROM CSHARP)
ORDER BY ID ASC;