# SELECT ID, FISH_NAME, LENGTH
# FROM FISH_NAME_INFO AS C
# RIGHT JOIN (
#     SELECT A.ID, A.FISH_TYPE, B.LENGTH
#     FROM FISH_INFO AS A
#     RIGHT JOIN (
#         SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
#         FROM FISH_INFO
#         GROUP BY FISH_TYPE
#         ) AS B ON A.LENGTH = B.LENGTH
#     WHERE A.FISH_TYPE = B.FISH_TYPE
#     ) AS D ON C.FISH_TYPE = D.FISH_TYPE
# ORDER BY ID ASC;

WITH MAX_RANK AS (
    SELECT ID, FISH_TYPE, LENGTH,
    RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RANKING
    FROM FISH_INFO
)

SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM MAX_RANK AS A
LEFT JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
WHERE RANKING = 1
ORDER BY ID ASC;