SELECT ID, FISH_NAME, LENGTH
FROM FISH_NAME_INFO AS C
RIGHT JOIN (
    SELECT A.ID, A.FISH_TYPE, B.LENGTH
    FROM FISH_INFO AS A
    RIGHT JOIN (
        SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE
        ) AS B ON A.LENGTH = B.LENGTH
    WHERE A.FISH_TYPE = B.FISH_TYPE
    ) AS D ON C.FISH_TYPE = D.FISH_TYPE
ORDER BY ID ASC;
