-- 코드를 작성해주세요
# SELECT SUM(A.SCORE) AS SCORE, A.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
# FROM HR_GRADE AS A
# LEFT JOIN HR_EMPLOYEES AS B ON A.EMP_NO = B.EMP_NO
# GROUP BY A.EMP_NO
# ORDER BY SCORE DESC
# LIMIT 1;

WITH MAX_SCORE AS (
    SELECT SUM(SCORE) AS SCORE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
)

SELECT SCORE, MAX_SCORE.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM MAX_SCORE, HR_EMPLOYEES
WHERE MAX_SCORE.EMP_NO = HR_EMPLOYEES.EMP_NO;