-- 코드를 입력하세요
WITH TOTAL_SALES AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE  DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01"
    GROUP BY BOOK_ID
)

SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM TOTAL_SALES AS B
INNER JOIN BOOK AS A ON A.BOOK_ID = B.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;