-- 코드를 작성해주세요
WITH DEV_FE AS (
    SELECT ID
    FROM DEVELOPERS
    WHERE 
    SKILL_CODE & (
        SELECT SUM(CODE)
        FROM SKILLCODES
        WHERE CATEGORY = "Front End"
        GROUP BY CATEGORY
    ) <> 0
), DEV_PY AS (
    SELECT ID
    FROM DEVELOPERS
    WHERE SKILL_CODE & (
        SELECT CODE
        FROM SKILLCODES
        WHERE NAME = "Python"
    ) <> 0
), DEV_CSHARP AS (
    SELECT ID
    FROM DEVELOPERS
    WHERE SKILL_CODE & (
        SELECT CODE
        FROM SKILLCODES
        WHERE NAME = "C#"
    ) <> 0
)

SELECT (
    CASE
    WHEN ID IN (SELECT ID FROM DEV_FE) 
        AND ID IN (SELECT ID FROM DEV_PY)
    THEN "A"
    WHEN ID IN (SELECT ID FROM DEV_CSHARP)
    THEN "B"
    WHEN ID IN (SELECT ID FROM DEV_FE)
    THEN "C"
    END
) AS GRADE, ID, EMAIL
FROM DEVELOPERS
WHERE ID IN (SELECT ID FROM DEV_FE)
    OR ID IN (SELECT ID FROM DEV_CSHARP)
ORDER BY GRADE ASC, ID ASC;
